export const BOOKINGS_LIST_REQUEST = "BOOKINGS_LIST_REQUEST";
export const BOOKINGS_LIST_SUCCESS = "BOOKINGS_LIST_SUCCESS";
export const BOOKINGS_LIST_FAIL = "BOOKINGS_LIST_FAIL";

export const BOOKINGS_CREATE_REQUEST = "BOOKINGS_CREATE_REQUEST";
export const BOOKINGS_CREATE_SUCCESS = "BOOKINGS_CREATE_SUCCESS";
export const BOOKINGS_CREATE_FAIL = "BOOKINGS_CREATE_FAIL";

export const BOOKINGS_UPDATE_REQUEST = "BOOKINGS_UPDATE_REQUEST";
export const BOOKINGS_UPDATE_SUCCESS = "BOOKINGS_UPDATE_SUCCESS";
export const BOOKINGS_UPDATE_FAIL = "BOOKINGS_UPDATE_FAIL";

export const BOOKINGS_DELETE_REQUEST = "BOOKINGS_DELETE_REQUEST";
export const BOOKINGS_DELETE_SUCCESS = "BOOKINGS_DELETE_SUCCESS";
export const BOOKINGS_DELETE_FAIL = "BOOKINGS_DELETE_FAIL";
