export const BUILDINGS_LIST_REQUEST = "BUILDINGS_LIST_REQUEST";
export const BUILDINGS_LIST_SUCCESS = "BUILDINGS_LIST_SUCCESS";
export const BUILDINGS_LIST_FAIL = "BUILDINGS_LIST_FAIL";
export const BUILDING_DESKS_REQUEST = "BUILDING_DESKS_REQUEST";
export const BUILDING_DESKS_SUCCESS = "BUILDING_DESKS_SUCCESS";
export const BUILDING_DESKS_FAIL = "BUILDING_DESKS_FAIL";